
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pablo
 */
public class Interfaz_Arbol extends javax.swing.JFrame {

    private final Arbol NuestroArbol = new Arbol();
    private String CadenaAr;
    /**
     * Creates new form Interfaz_Arbol
     */
    public Interfaz_Arbol() {
        initComponents();
    }

private void cargarDatosDesdeArchivo(String nombreArchivo) {
    try {
        File archivo = new File(nombreArchivo);
        if (!archivo.exists()) {
            archivo.createNewFile();
        }
        
        try (BufferedReader reader = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                NuestroArbol.insertar(linea);
            }
        }
    } catch (IOException e) {
        System.err.println("Error al cargar los datos desde el archivo: " + e.getMessage());
    }
}

private void mostrarDatosEnTextArea() {
    StringBuilder sb = new StringBuilder();
    mostrarDatosEnOrden(NuestroArbol.raiz, sb);
    ArbolActualTxT.setText(sb.toString());
}

private void mostrarDatosEnOrden(Nodo nodo, StringBuilder sb) {
    if (nodo != null) {
        mostrarDatosEnOrden(nodo.getIzquierda(), sb);
        sb.append(nodo.dato).append("\n");
        mostrarDatosEnOrden(nodo.getDerecha(), sb);
    }
}

private void guardarDatosEnArchivo(String nombreArchivo) {
    try {
        File archivo = new File(nombreArchivo);
        if (!archivo.exists()) {
            archivo.createNewFile();
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {
            guardarDatosEnOrden(NuestroArbol.raiz, writer);
        }
    } catch (IOException e) {
        System.err.println("Error al guardar los datos en el archivo: " + e.getMessage());
    }
}

private void guardarDatosEnOrden(Nodo nodo, BufferedWriter writer) throws IOException {
    if (nodo != null) {
        guardarDatosEnOrden(nodo.getIzquierda(), writer);
        writer.write(nodo.dato);
        writer.newLine();
        guardarDatosEnOrden(nodo.getDerecha(), writer);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ArbolActualTxT = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ResultadoTxT = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GuardarBtm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        IngresoTxT = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        IngresarBtm = new javax.swing.JButton();
        LeerBtm = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        ArbolActualTxT.setBackground(new java.awt.Color(51, 51, 51));
        ArbolActualTxT.setColumns(20);
        ArbolActualTxT.setForeground(new java.awt.Color(204, 255, 255));
        ArbolActualTxT.setRows(5);
        jScrollPane2.setViewportView(ArbolActualTxT);

        ResultadoTxT.setBackground(new java.awt.Color(51, 51, 51));
        ResultadoTxT.setColumns(20);
        ResultadoTxT.setForeground(new java.awt.Color(204, 255, 255));
        ResultadoTxT.setRows(5);
        jScrollPane3.setViewportView(ResultadoTxT);

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resultado");

        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actual");

        GuardarBtm.setText("Guardar");
        GuardarBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBtmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuardarBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(109, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(752, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuardarBtm, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(56, 56, 56)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 454, 849, -1));

        IngresoTxT.setBackground(new java.awt.Color(51, 51, 51));
        IngresoTxT.setColumns(20);
        IngresoTxT.setForeground(new java.awt.Color(204, 255, 204));
        IngresoTxT.setRows(5);
        jScrollPane1.setViewportView(IngresoTxT);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 17, 530, 35));

        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 17, 93, 35));

        IngresarBtm.setText("Ingresar");
        IngresarBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBtmActionPerformed(evt);
            }
        });
        jPanel1.add(IngresarBtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        LeerBtm.setText("Leer");
        LeerBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerBtmActionPerformed(evt);
            }
        });
        jPanel1.add(LeerBtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 70, -1));

        jButton1.setText("PosOrden");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 90, -1));

        jButton2.setText("InOrden");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 90, -1));

        jButton3.setText("PreOrden");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBtmActionPerformed
        String NodoIng = IngresoTxT.getText();
        NuestroArbol.insertar(NodoIng);
        
        CadenaAr = CadenaAr + " - " + NodoIng;
        ResultadoTxT.setText(CadenaAr);
    }//GEN-LAST:event_IngresarBtmActionPerformed

    private void LeerBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerBtmActionPerformed
        NuestroArbol.vaciar(); // Eliminar todos los elementos del árbol
        CadenaAr = ""; // Vaciar el StringBuilder
        
        cargarDatosDesdeArchivo("nombre_del_archivo.txt");
        mostrarDatosEnTextArea();
    }//GEN-LAST:event_LeerBtmActionPerformed

    private void GuardarBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBtmActionPerformed
        guardarDatosEnArchivo("nombre_del_archivo.txt");
    }//GEN-LAST:event_GuardarBtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Arbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ArbolActualTxT;
    private javax.swing.JButton GuardarBtm;
    private javax.swing.JButton IngresarBtm;
    private javax.swing.JTextArea IngresoTxT;
    private javax.swing.JButton LeerBtm;
    private javax.swing.JTextArea ResultadoTxT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
